/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD2;

import org.junit.Test;
import td2.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
       
    }
}
